// 4 trend-based career courses. Each = guideline pages (not full lessons): what to learn,
// where to read/watch, step-by-step, and a "worth" increment (₹/yr) earned on Finish.
// Structure: course -> units[] -> topics[] (each topic is one page).

const R = (label, url) => ({ label, url });

export const COURSES = [
  // ───────────────────────────── 1. COMPUTER SCIENCE ─────────────────────────────
  {
    slug: 'computer-science',
    title: 'Computer Science & Software Engineering',
    short: 'Computer Science',
    icon: 'code',
    accent: '#1fe06a',
    blurb: 'The core CS foundation every product company tests for — DSA, systems, and how real software is built.',
    salary: { start: 350000, target: 1200000 },
    trend: 'Hot',
    units: [
      {
        title: 'Programming Foundations',
        topics: [
          { slug: 'pick-a-language', title: 'Pick ONE language and go deep', read: 6, worth: 40000,
            intro: 'Recruiters don’t care how many languages you list — they care that you can solve problems fluently in one. Pick Python (fastest to interview-ready) or Java/C++ (strong for product companies).',
            concepts: ['Variables, types, control flow', 'Functions & recursion', 'Reading docs instead of tutorials', 'Reading error messages'],
            steps: ['Choose Python if unsure.', 'Finish a 4-hour syntax crash course.', 'Re-build 5 small programs from memory (no copy-paste).', 'Push them to a GitHub repo today.'],
            resources: [R('Python — freeCodeCamp 4hr', 'https://www.youtube.com/watch?v=rfscVS0vtbw'), R('GeeksforGeeks Python', 'https://www.geeksforgeeks.org/python-programming-language/')] },
          { slug: 'problem-solving', title: 'Problem-solving mindset', read: 5, worth: 35000,
            intro: 'Before DSA, learn to break a problem into inputs, outputs, and steps. This single skill separates people who freeze in interviews from people who think out loud.',
            concepts: ['Decompose the problem', 'Brute force first, optimise later', 'Dry-run with examples', 'Edge cases'],
            steps: ['Solve 10 “Easy” problems on paper before coding.', 'Always state brute force out loud first.', 'Time-box each to 20 min, then read the editorial.'],
            resources: [R('LeetCode (Easy set)', 'https://leetcode.com/problemset/'), R('How to think about problems', 'https://www.geeksforgeeks.org/how-to-start-learning-dsa/')] },
        ],
      },
      {
        title: 'Data Structures & Algorithms',
        topics: [
          { slug: 'arrays-strings', title: 'Arrays & strings', read: 7, worth: 55000,
            intro: 'Roughly 40% of entry-level coding rounds are arrays/strings. Master the patterns, not random problems.',
            concepts: ['Two pointers', 'Sliding window', 'Prefix sums', 'Hash maps for O(n) lookup'],
            steps: ['Learn each pattern from 1 example.', 'Solve 5 problems per pattern.', 'Re-solve any you failed after 2 days.'],
            resources: [R('NeetCode roadmap', 'https://neetcode.io/roadmap'), R('GfG Arrays', 'https://www.geeksforgeeks.org/array-data-structure/')] },
          { slug: 'hashing-stacks-queues', title: 'Hashing, stacks & queues', read: 6, worth: 45000,
            intro: 'These show up constantly and are quick wins once the pattern clicks.',
            concepts: ['Hash maps & sets', 'Stack for “last seen” problems', 'Queue / deque', 'Monotonic stack'],
            steps: ['Implement each from scratch once.', 'Solve 4 problems each.', 'Note which real problems map to which structure.'],
            resources: [R('GfG Stack', 'https://www.geeksforgeeks.org/stack-data-structure/'), R('NeetCode', 'https://neetcode.io/')] },
          { slug: 'trees-graphs', title: 'Trees & graphs (the differentiator)', read: 9, worth: 70000,
            intro: 'Most freshers skip these and get filtered. Knowing BFS/DFS cold puts you ahead of the majority.',
            concepts: ['Binary trees & traversals', 'BFS & DFS', 'Recursion on trees', 'Graph as adjacency list'],
            steps: ['Learn DFS + BFS templates by heart.', 'Solve 8 tree + 6 graph problems.', 'Draw every problem before coding.'],
            resources: [R('GfG Graph', 'https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/'), R('Tree visualizer', 'https://visualgo.net/en')] },
          { slug: 'dp-intro', title: 'Dynamic programming (just enough)', read: 8, worth: 60000,
            intro: 'You don’t need to be a DP master for entry roles — you need to recognise it and solve the classic 10.',
            concepts: ['Overlapping subproblems', 'Memoization', 'Bottom-up tables', 'The classic 10 (knapsack, LIS, coin change…)'],
            steps: ['Learn memoization on Fibonacci.', 'Do the “classic 10”.', 'Stop there until you’re interviewing at top firms.'],
            resources: [R('DP for beginners', 'https://www.geeksforgeeks.org/dynamic-programming/'), R('NeetCode DP', 'https://neetcode.io/roadmap')] },
        ],
      },
      {
        title: 'Computer Systems',
        topics: [
          { slug: 'os-basics', title: 'Operating systems basics', read: 6, worth: 40000,
            intro: 'Product companies ask OS in interviews. You need the vocabulary, not a degree.',
            concepts: ['Process vs thread', 'Scheduling', 'Deadlock', 'Memory & paging'],
            steps: ['Read each topic’s one-pager.', 'Be able to explain process vs thread in 2 lines.', 'Make a 1-page cheat sheet.'],
            resources: [R('GfG OS', 'https://www.geeksforgeeks.org/operating-systems/'), R('OS crash course', 'https://www.youtube.com/watch?v=26QPDBe-NB8')] },
          { slug: 'dbms-sql', title: 'DBMS & SQL', read: 7, worth: 55000,
            intro: 'SQL is the single most reused skill across every tech job. Non-negotiable.',
            concepts: ['SELECT / WHERE / JOIN / GROUP BY', 'Normalization', 'Indexes', 'Transactions & ACID'],
            steps: ['Do 40 SQL queries on a sandbox.', 'Learn the 4 JOIN types cold.', 'Explain a primary vs foreign key.'],
            resources: [R('SQLBolt (interactive)', 'https://sqlbolt.com/'), R('GfG DBMS', 'https://www.geeksforgeeks.org/dbms/')] },
        ],
      },
      {
        title: 'Computer Networks',
        topics: [
          { slug: 'networking-basics', title: 'Networking essentials', read: 6, worth: 40000,
            intro: 'Enough networking to answer “what happens when you type a URL?” — a top-asked interview question.',
            concepts: ['HTTP/HTTPS', 'TCP vs UDP', 'DNS', 'OSI layers (just the idea)'],
            steps: ['Learn the URL→render flow.', 'Memorise HTTP status codes 200/301/404/500.', 'Explain TCP handshake in 2 lines.'],
            resources: [R('What happens when you type a URL', 'https://github.com/alex/what-happens-when'), R('GfG Networks', 'https://www.geeksforgeeks.org/computer-network-tutorials/')] },
        ],
      },
      {
        title: 'Getting Hired',
        topics: [
          { slug: 'github-resume', title: 'A resume + GitHub that pass the 8-second scan', read: 6, worth: 50000,
            intro: 'A recruiter spends ~8 seconds. One real project beats ten tutorials.',
            concepts: ['1-page resume', 'Quantified impact', 'Pinned GitHub repos', 'Clean READMEs'],
            steps: ['Build 1 non-tutorial project.', 'Write its README like a product page.', 'Pin 3 repos. Use a 1-page resume template.'],
            resources: [R('Resume guide', 'https://www.techinterviewhandbook.org/resume/'), R('Good README', 'https://www.makeareadme.com/')] },
          { slug: 'interview-prep', title: 'Cracking the entry-level interview', read: 7, worth: 65000,
            intro: 'Interviews are a learnable game: pattern-based DSA + clear communication + basic CS theory.',
            concepts: ['Think out loud', 'Clarify before coding', 'Behavioural (STAR)', 'Mock interviews'],
            steps: ['Do 3 mock interviews.', 'Prepare 5 STAR stories.', 'Re-solve every problem you missed.'],
            resources: [R('Tech Interview Handbook', 'https://www.techinterviewhandbook.org/'), R('Pramp mock interviews', 'https://www.pramp.com/')] },
        ],
      },
      {
        title: 'Core CS Extras',
        topics: [
          { slug: 'sorting-searching', title: 'Sorting & searching', read: 6, worth: 45000,
            intro: 'You rarely write sort algorithms at work, but interviews love them — and binary search is a genuine super-power.',
            concepts: ['Built-in sort + custom comparators', 'Binary search (and on the answer)', 'Merge vs quick sort idea', 'Time/space tradeoffs'],
            steps: ['Learn binary search cold — it’s the highest ROI.', 'Solve 6 binary-search problems.', 'Know the complexity of each sort.'],
            resources: [R('Binary search patterns', 'https://www.geeksforgeeks.org/binary-search/'), R('NeetCode', 'https://neetcode.io/roadmap')] },
          { slug: 'oop-design', title: 'OOP & low-level design basics', read: 6, worth: 50000,
            intro: 'Many entry interviews ask you to “design a class” — OOP fundamentals make that easy points.',
            concepts: ['Classes & objects', 'Encapsulation, inheritance, polymorphism', 'SOLID (just the idea)', 'Design a simple system (parking lot, etc.)'],
            steps: ['Explain the 4 OOP pillars with examples.', 'Design 2 classic LLD problems on paper.', 'Refactor old code to be cleaner.'],
            resources: [R('OOP concepts', 'https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/'), R('LLD primer', 'https://github.com/prasadgujar/low-level-design-primer')] },
        ],
      },
    ],
  },

  // ───────────────────────────── 2. DATA SCIENCE & AI ─────────────────────────────
  {
    slug: 'data-science-ai',
    title: 'Data Science & AI',
    short: 'Data Science & AI',
    icon: 'data',
    accent: '#c9f23e',
    blurb: 'The fastest-growing pay band. Go from spreadsheets to shipping a model recruiters can actually see.',
    salary: { start: 400000, target: 1800000 },
    trend: 'Surging',
    units: [
      {
        title: 'Data Foundations',
        topics: [
          { slug: 'python-for-data', title: 'Python for data (NumPy + Pandas)', read: 7, worth: 55000,
            intro: 'Pandas is to data science what Excel is to finance. This is the daily driver.',
            concepts: ['DataFrames', 'Filtering & groupby', 'Missing data', 'Vectorised ops'],
            steps: ['Do a Pandas crash course.', 'Clean one messy public dataset.', 'Re-create 10 Excel tasks in Pandas.'],
            resources: [R('Pandas in 1 hr', 'https://www.youtube.com/watch?v=vmEHCJofslg'), R('Kaggle Pandas', 'https://www.kaggle.com/learn/pandas')] },
          { slug: 'stats-essentials', title: 'Statistics you actually use', read: 6, worth: 45000,
            intro: 'You don’t need a stats degree — you need the 20% that explains 80% of decisions.',
            concepts: ['Mean/median/variance', 'Distributions', 'Correlation vs causation', 'p-values (the intuition)'],
            steps: ['Learn descriptive stats.', 'Understand normal distribution.', 'Be able to explain correlation ≠ causation.'],
            resources: [R('StatQuest (YouTube)', 'https://www.youtube.com/c/joshstarmer'), R('Khan Academy Stats', 'https://www.khanacademy.org/math/statistics-probability')] },
          { slug: 'sql-for-data', title: 'SQL for analysts', read: 6, worth: 50000,
            intro: '90% of data jobs run on SQL daily. It’s the most reusable skill in this course.',
            concepts: ['Joins', 'Window functions', 'CTEs', 'Aggregations'],
            steps: ['Finish SQLBolt.', 'Do 30 analytics queries.', 'Learn window functions (RANK, LAG).'],
            resources: [R('SQLBolt', 'https://sqlbolt.com/'), R('Mode SQL tutorial', 'https://mode.com/sql-tutorial/')] },
        ],
      },
      {
        title: 'Telling Stories with Data',
        topics: [
          { slug: 'eda-viz', title: 'EDA & visualization', read: 7, worth: 55000,
            intro: 'Hiring managers love candidates who find insight, not just train models.',
            concepts: ['Exploratory analysis', 'Matplotlib/Seaborn', 'Dashboards', 'Insight → story'],
            steps: ['Do EDA on a Kaggle dataset.', 'Make 5 clear charts.', 'Write 3 insights a non-tech person understands.'],
            resources: [R('Kaggle Data Viz', 'https://www.kaggle.com/learn/data-visualization'), R('Seaborn gallery', 'https://seaborn.pydata.org/examples/index.html')] },
          { slug: 'excel-bi', title: 'Excel + a BI tool (Power BI/Tableau)', read: 5, worth: 40000,
            intro: 'Most analyst roles still expect Excel + one BI tool. Quick to learn, high signal on a resume.',
            concepts: ['Pivot tables', 'VLOOKUP/XLOOKUP', 'BI dashboards', 'KPIs'],
            steps: ['Master pivot tables.', 'Build 1 dashboard in Power BI or Tableau Public.', 'Publish it publicly.'],
            resources: [R('Tableau Public', 'https://public.tableau.com/'), R('Power BI learning', 'https://learn.microsoft.com/power-bi/')] },
        ],
      },
      {
        title: 'Machine Learning',
        topics: [
          { slug: 'ml-basics', title: 'Classic ML with scikit-learn', read: 9, worth: 80000,
            intro: 'This is where pay jumps. Understand the workflow before deep learning.',
            concepts: ['Train/test split', 'Regression & classification', 'Overfitting', 'Metrics (accuracy, F1, ROC)'],
            steps: ['Do Kaggle Intro to ML.', 'Train 3 models end-to-end.', 'Submit to a Kaggle competition.'],
            resources: [R('Kaggle Intro to ML', 'https://www.kaggle.com/learn/intro-to-machine-learning'), R('scikit-learn docs', 'https://scikit-learn.org/stable/')] },
          { slug: 'feature-eval', title: 'Features, evaluation & leakage', read: 6, worth: 55000,
            intro: 'Beginners obsess over models; pros obsess over data leakage and honest evaluation.',
            concepts: ['Feature engineering', 'Cross-validation', 'Data leakage', 'Baseline first'],
            steps: ['Always build a dumb baseline first.', 'Use cross-validation, not single split.', 'Hunt for leakage in your features.'],
            resources: [R('Kaggle Feature Eng.', 'https://www.kaggle.com/learn/feature-engineering'), R('GfG ML', 'https://www.geeksforgeeks.org/machine-learning/')] },
        ],
      },
      {
        title: 'AI & LLMs (the trend)',
        topics: [
          { slug: 'llm-apps', title: 'Building with LLMs & APIs', read: 7, worth: 90000,
            intro: 'The single highest-leverage 2026 skill: shipping apps on top of LLM APIs.',
            concepts: ['Prompting', 'Embeddings & RAG', 'Calling an LLM API', 'Vector search'],
            steps: ['Build a small RAG chatbot over your notes.', 'Use an LLM API (xAI/OpenAI).', 'Deploy it so others can try it.'],
            resources: [R('RAG explained', 'https://www.youtube.com/watch?v=T-D1OfcDW1M'), R('xAI API docs', 'https://docs.x.ai/')] },
          { slug: 'deep-learning-taste', title: 'A taste of deep learning', read: 6, worth: 55000,
            intro: 'Enough neural-net intuition to speak the language — go deep only if you target ML-engineer roles.',
            concepts: ['Neural net intuition', 'PyTorch basics', 'Transfer learning', 'When NOT to use DL'],
            steps: ['Train one image classifier with transfer learning.', 'Understand why DL needs lots of data.', 'Stop unless you’re going ML-engineer.'],
            resources: [R('fast.ai', 'https://course.fast.ai/'), R('PyTorch 60-min blitz', 'https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html')] },
        ],
      },
      {
        title: 'Portfolio & Hiring',
        topics: [
          { slug: 'ds-portfolio', title: 'A portfolio that gets interviews', read: 6, worth: 60000,
            intro: 'In data roles, a public notebook + dashboard beats a certificate every time.',
            concepts: ['End-to-end project', 'Kaggle profile', 'Clear writeups', 'GitHub'],
            steps: ['Ship 2 end-to-end projects.', 'Write each up like a case study.', 'Make a Kaggle + GitHub profile.'],
            resources: [R('Kaggle', 'https://www.kaggle.com/'), R('DS resume tips', 'https://www.techinterviewhandbook.org/resume/')] },
        ],
      },
      {
        title: 'Going Pro',
        topics: [
          { slug: 'data-cleaning', title: 'Data cleaning & wrangling', read: 6, worth: 45000,
            intro: 'Real data is messy. Data scientists spend ~70% of time here — being good at it is a quiet superpower.',
            concepts: ['Missing values', 'Outliers', 'Type fixes & parsing dates', 'Joining messy sources'],
            steps: ['Clean one truly messy public dataset.', 'Document every decision you made.', 'Turn it into a reusable cleaning function.'],
            resources: [R('Kaggle Data Cleaning', 'https://www.kaggle.com/learn/data-cleaning'), R('Pandas cleaning', 'https://pandas.pydata.org/docs/user_guide/missing_data.html')] },
          { slug: 'ab-testing', title: 'A/B testing & experiments', read: 6, worth: 55000,
            intro: 'Product companies love analysts who can reason about experiments, not just charts.',
            concepts: ['Control vs variant', 'Statistical significance', 'Sample size', 'Reading results honestly'],
            steps: ['Learn the A/B testing mental model.', 'Compute significance on a sample dataset.', 'Explain a result to a non-tech person.'],
            resources: [R('A/B testing (Udacity free)', 'https://www.udacity.com/course/ab-testing--ud257'), R('StatQuest', 'https://www.youtube.com/c/joshstarmer')] },
          { slug: 'mlops-taste', title: 'Shipping & MLOps taste', read: 6, worth: 60000,
            intro: 'A model in a notebook earns nothing. Knowing how to serve one makes you instantly more hireable.',
            concepts: ['Serialise a model', 'Serve via an API', 'Streamlit/Gradio demos', 'Versioning data & models'],
            steps: ['Wrap a model in a FastAPI/Gradio app.', 'Deploy a Streamlit demo.', 'Share the live link in your portfolio.'],
            resources: [R('Streamlit', 'https://streamlit.io/'), R('Gradio', 'https://www.gradio.app/')] },
        ],
      },
    ],
  },

  // ───────────────────────────── 3. WEB & APP DEVELOPMENT ─────────────────────────────
  {
    slug: 'web-app-development',
    title: 'Web & App Development',
    short: 'Web/App Dev',
    icon: 'web',
    accent: '#2be3c0',
    blurb: 'The fastest path to a paid job or freelancing — because you can SHOW what you built.',
    salary: { start: 300000, target: 1500000 },
    trend: 'Evergreen',
    units: [
      {
        title: 'The Web Foundations',
        topics: [
          { slug: 'html-css', title: 'HTML & CSS that look modern', read: 6, worth: 40000,
            intro: 'You can be hireable on the front end faster than any other path because output is visible.',
            concepts: ['Semantic HTML', 'Flexbox & Grid', 'Responsive design', 'A CSS framework (Tailwind)'],
            steps: ['Rebuild 3 real sites pixel-close.', 'Learn Flexbox + Grid.', 'Make them mobile-responsive.'],
            resources: [R('freeCodeCamp Responsive', 'https://www.freecodecamp.org/learn/2022/responsive-web-design/'), R('Tailwind docs', 'https://tailwindcss.com/docs')] },
          { slug: 'javascript', title: 'JavaScript (the language of the web)', read: 8, worth: 60000,
            intro: 'JS is the one language that runs the whole web. Get fluent before any framework.',
            concepts: ['DOM manipulation', 'Async/await & fetch', 'Array methods', 'ES6+'],
            steps: ['Build 5 vanilla-JS mini apps.', 'Master map/filter/reduce.', 'Fetch from a public API.'],
            resources: [R('javascript.info', 'https://javascript.info/'), R('JS30 (30 projects)', 'https://javascript30.com/')] },
        ],
      },
      {
        title: 'Modern Front End',
        topics: [
          { slug: 'react', title: 'React (the industry default)', read: 8, worth: 80000,
            intro: 'React is on the most job listings. Learn it after solid JS, not before.',
            concepts: ['Components & props', 'State & hooks', 'Lists & forms', 'Fetching data'],
            steps: ['Build a todo + a weather app.', 'Learn useState/useEffect deeply.', 'Deploy on Vercel.'],
            resources: [R('react.dev learn', 'https://react.dev/learn'), R('Scrimba React', 'https://scrimba.com/learn/learnreact')] },
          { slug: 'nextjs', title: 'Next.js & deployment', read: 7, worth: 70000,
            intro: 'Next.js + Vercel is the fastest way to put a real, fast site online for free.',
            concepts: ['Routing & pages', 'Server vs client components', 'API routes', 'Deploy to Vercel'],
            steps: ['Convert one React app to Next.js.', 'Add an API route.', 'Deploy with a custom-looking URL.'],
            resources: [R('Next.js learn', 'https://nextjs.org/learn'), R('Vercel deploy', 'https://vercel.com/docs')] },
        ],
      },
      {
        title: 'The Back End',
        topics: [
          { slug: 'node-api', title: 'Node + REST APIs', read: 7, worth: 65000,
            intro: 'Full-stack devs get paid more. Learn to build the API your front end talks to.',
            concepts: ['Express routes', 'REST design', 'Auth basics', 'Status codes'],
            steps: ['Build a CRUD API.', 'Connect it to your React app.', 'Add login.'],
            resources: [R('Node + Express', 'https://www.youtube.com/watch?v=Oe421EPjeBE'), R('REST guide', 'https://restfulapi.net/')] },
          { slug: 'databases', title: 'Databases (SQL + a hosted DB)', read: 6, worth: 55000,
            intro: 'A real app needs to store data. A free Postgres/Supabase backend is enough to look professional.',
            concepts: ['Relational basics', 'CRUD with a DB', 'Supabase/Postgres', 'Env vars & secrets'],
            steps: ['Spin up a free Supabase project.', 'Wire CRUD to it.', 'Keep keys in env vars.'],
            resources: [R('Supabase docs', 'https://supabase.com/docs'), R('SQLBolt', 'https://sqlbolt.com/')] },
        ],
      },
      {
        title: 'Mobile (optional fast lane)',
        topics: [
          { slug: 'react-native', title: 'Apps with React Native / Expo', read: 6, worth: 50000,
            intro: 'If you already know React, you can ship a real phone app in a weekend with Expo.',
            concepts: ['Expo workflow', 'Reusing React skills', 'Native components', 'Publishing'],
            steps: ['Build one Expo app.', 'Run it on your own phone.', 'Publish a build.'],
            resources: [R('Expo docs', 'https://docs.expo.dev/'), R('React Native', 'https://reactnative.dev/')] },
        ],
      },
      {
        title: 'Ship & Get Paid',
        topics: [
          { slug: 'portfolio-site', title: 'A portfolio + 3 real projects', read: 6, worth: 60000,
            intro: 'For devs, the portfolio IS the resume. Three deployed projects beat any certificate.',
            concepts: ['Live deployments', 'Case-study writeups', 'Clean GitHub', 'A personal site'],
            steps: ['Deploy 3 projects live.', 'Write a short case study for each.', 'Build a 1-page portfolio site.'],
            resources: [R('Vercel', 'https://vercel.com/'), R('GitHub Pages', 'https://pages.github.com/')] },
          { slug: 'freelance-jobs', title: 'First job or freelance client', read: 6, worth: 70000,
            intro: 'Web skills can earn before a full-time job — through freelancing and local businesses.',
            concepts: ['Where jobs are', 'Cold outreach', 'Freelance platforms', 'Pricing your first gig'],
            steps: ['Apply to 20 junior roles.', 'Offer 2 local businesses a site.', 'List a gig on a freelance platform.'],
            resources: [R('Upwork', 'https://www.upwork.com/'), R('Junior jobs', 'https://www.linkedin.com/jobs/')] },
        ],
      },
      {
        title: 'Pro Toolkit',
        topics: [
          { slug: 'git-deploy', title: 'Git & deploying for free', read: 5, worth: 35000,
            intro: 'Employers expect Git fluency and a live URL. Both are easy wins that many freshers skip.',
            concepts: ['Branches & pull requests', 'Vercel/Netlify deploys', 'Env vars', 'Custom domains'],
            steps: ['Learn the branch → PR flow.', 'Deploy a project on Vercel.', 'Add it to your resume as a live link.'],
            resources: [R('Learn Git Branching', 'https://learngitbranching.js.org/'), R('Vercel', 'https://vercel.com/docs')] },
          { slug: 'typescript', title: 'TypeScript', read: 6, worth: 55000,
            intro: 'Most serious React/Node jobs now expect TypeScript. It’s a small add-on with a big salary signal.',
            concepts: ['Types & interfaces', 'Typing props & functions', 'Generics (lightly)', 'Why teams love it'],
            steps: ['Convert one JS project to TS.', 'Type all props and API responses.', 'Fix every red squiggle.'],
            resources: [R('TypeScript handbook', 'https://www.typescriptlang.org/docs/handbook/intro.html'), R('TS for JS devs', 'https://www.totaltypescript.com/tutorials')] },
          { slug: 'auth-security', title: 'Auth & web security basics', read: 6, worth: 55000,
            intro: 'Knowing how login + basic security work separates “I did a tutorial” from “I can build real apps.”',
            concepts: ['Sessions vs JWT', 'Hashing passwords', 'HTTPS & CORS', 'Common vulns (XSS, SQLi)'],
            steps: ['Add real auth to one app.', 'Never store plain passwords.', 'Learn the OWASP top-5 by name.'],
            resources: [R('Auth basics', 'https://www.youtube.com/watch?v=2PPSXonhIck'), R('OWASP Top 10', 'https://owasp.org/www-project-top-ten/')] },
          { slug: 'testing-perf', title: 'Testing & performance', read: 5, worth: 45000,
            intro: 'A little testing + speed awareness makes your projects look senior and pass code reviews.',
            concepts: ['Unit tests', 'Lighthouse scores', 'Lazy loading & images', 'Core Web Vitals'],
            steps: ['Add a few tests to a project.', 'Run Lighthouse, fix the reds.', 'Optimise images + lazy-load.'],
            resources: [R('Testing Library', 'https://testing-library.com/'), R('web.dev performance', 'https://web.dev/learn/performance/')] },
        ],
      },
    ],
  },

  // ───────────────────────────── 4. CLOUD & DEVOPS ─────────────────────────────
  {
    slug: 'cloud-devops',
    title: 'Cloud & DevOps',
    short: 'Cloud & DevOps',
    icon: 'cloud',
    accent: '#6ee85a',
    blurb: 'Fewer people learn it, companies desperately need it — which is exactly why it pays.',
    salary: { start: 400000, target: 2000000 },
    trend: 'High demand',
    units: [
      {
        title: 'Linux & Command Line',
        topics: [
          { slug: 'linux-cli', title: 'Linux & the terminal', read: 6, worth: 45000,
            intro: 'Every cloud server is Linux. Comfort in the terminal is the entry ticket.',
            concepts: ['File system & permissions', 'Core commands', 'Pipes & grep', 'Processes'],
            steps: ['Learn 30 core commands.', 'Live in the terminal for a week.', 'Write a small bash script.'],
            resources: [R('Linux Journey', 'https://linuxjourney.com/'), R('GfG Linux', 'https://www.geeksforgeeks.org/linux-tutorial/')] },
          { slug: 'git', title: 'Git & GitHub workflows', read: 5, worth: 40000,
            intro: 'Version control is mandatory everywhere. DevOps lives in Git.',
            concepts: ['Commit/branch/merge', 'Pull requests', 'Resolving conflicts', '.gitignore'],
            steps: ['Learn branch + PR flow.', 'Make 10 commits on a real repo.', 'Resolve one merge conflict on purpose.'],
            resources: [R('Learn Git Branching', 'https://learngitbranching.js.org/'), R('GitHub docs', 'https://docs.github.com/')] },
        ],
      },
      {
        title: 'Cloud Fundamentals',
        topics: [
          { slug: 'cloud-basics', title: 'Cloud basics (AWS/Azure/GCP)', read: 7, worth: 65000,
            intro: 'Pick one cloud (AWS is most-hired) and learn the core building blocks.',
            concepts: ['Compute (EC2)', 'Storage (S3)', 'Networking (VPC)', 'IAM & security'],
            steps: ['Make a free-tier AWS account.', 'Deploy a static site to S3.', 'Spin up + SSH into one server.'],
            resources: [R('AWS Free Tier', 'https://aws.amazon.com/free/'), R('AWS Cloud Practitioner', 'https://www.aws.training/')] },
          { slug: 'cloud-cert', title: 'Get one cloud certification', read: 5, worth: 80000,
            intro: 'A single entry cloud cert is one of the best ROI moves for a fresher’s salary.',
            concepts: ['AWS Cloud Practitioner', 'Az-900 / GCP equivalent', 'Exam strategy', 'Hands-on labs'],
            steps: ['Pick AWS CCP or AZ-900.', 'Do a full prep course.', 'Book + pass the exam.'],
            resources: [R('AWS CCP', 'https://aws.amazon.com/certification/certified-cloud-practitioner/'), R('Azure AZ-900', 'https://learn.microsoft.com/credentials/certifications/azure-fundamentals/')] },
        ],
      },
      {
        title: 'Containers',
        topics: [
          { slug: 'docker', title: 'Docker', read: 7, worth: 70000,
            intro: 'Containers are the unit of modern deployment. Docker is the must-know.',
            concepts: ['Images vs containers', 'Dockerfile', 'docker-compose', 'Registries'],
            steps: ['Containerise one of your apps.', 'Write a Dockerfile from scratch.', 'Push the image to Docker Hub.'],
            resources: [R('Docker 101', 'https://www.docker.com/101-tutorial/'), R('Docker docs', 'https://docs.docker.com/get-started/')] },
          { slug: 'kubernetes', title: 'Kubernetes (just the basics)', read: 7, worth: 75000,
            intro: 'You don’t need to master K8s as a fresher — but knowing pods/deployments is a big differentiator.',
            concepts: ['Pods & deployments', 'Services', 'kubectl', 'When you actually need K8s'],
            steps: ['Run minikube locally.', 'Deploy your Docker app to it.', 'Learn 8 kubectl commands.'],
            resources: [R('Kubernetes basics', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/'), R('minikube', 'https://minikube.sigs.k8s.io/docs/start/')] },
        ],
      },
      {
        title: 'Automation (CI/CD + IaC)',
        topics: [
          { slug: 'cicd', title: 'CI/CD pipelines', read: 6, worth: 70000,
            intro: 'Automating build→test→deploy is the core of the DevOps job.',
            concepts: ['GitHub Actions', 'Build & test stages', 'Auto-deploy', 'Secrets'],
            steps: ['Add a GitHub Actions workflow.', 'Auto-deploy on every push.', 'Store secrets safely.'],
            resources: [R('GitHub Actions', 'https://docs.github.com/actions'), R('CI/CD explained', 'https://www.youtube.com/watch?v=scEDHsr3APg')] },
          { slug: 'iac-terraform', title: 'Infrastructure as Code (Terraform)', read: 6, worth: 65000,
            intro: 'Defining infra in code is what senior DevOps lives on — get an early taste.',
            concepts: ['Declarative infra', 'Terraform basics', 'State', 'Reproducible environments'],
            steps: ['Provision one cloud resource with Terraform.', 'Destroy + recreate it.', 'Read someone’s real .tf files.'],
            resources: [R('Terraform tutorials', 'https://developer.hashicorp.com/terraform/tutorials'), R('Terraform docs', 'https://developer.hashicorp.com/terraform/docs')] },
        ],
      },
      {
        title: 'Monitoring & Hiring',
        topics: [
          { slug: 'monitoring', title: 'Monitoring & observability', read: 5, worth: 50000,
            intro: 'Knowing how systems are watched in production makes you sound senior in interviews.',
            concepts: ['Logs/metrics/traces', 'Prometheus & Grafana', 'Alerts', 'Uptime'],
            steps: ['Add basic logging to an app.', 'Spin up a Grafana dashboard.', 'Set one alert.'],
            resources: [R('Grafana', 'https://grafana.com/tutorials/'), R('Prometheus', 'https://prometheus.io/docs/introduction/overview/')] },
          { slug: 'devops-hiring', title: 'Landing the DevOps role', read: 6, worth: 75000,
            intro: 'DevOps interviews reward projects + a clear story of automating something real.',
            concepts: ['A homelab/portfolio', 'Cert on resume', 'Scenario questions', 'Linux + cloud combo'],
            steps: ['Document one full pipeline project.', 'Put your cert on your resume.', 'Practise “how would you deploy X” questions.'],
            resources: [R('DevOps roadmap', 'https://roadmap.sh/devops'), R('Junior DevOps jobs', 'https://www.linkedin.com/jobs/')] },
        ],
      },
      {
        title: 'Cloud Extras',
        topics: [
          { slug: 'cloud-networking', title: 'Networking & DNS for cloud', read: 5, worth: 45000,
            intro: 'Half of all “my deploy is broken” problems are networking. Knowing the basics makes you the person who fixes them.',
            concepts: ['VPC / subnets idea', 'Ports & firewalls', 'DNS records (A, CNAME)', 'Load balancers'],
            steps: ['Map how a request reaches your server.', 'Point a domain with an A/CNAME record.', 'Open/close a port and watch the effect.'],
            resources: [R('DNS in 1 video', 'https://www.youtube.com/watch?v=72snZctFFtA'), R('AWS networking', 'https://aws.amazon.com/vpc/')] },
          { slug: 'serverless', title: 'Serverless & functions', read: 5, worth: 55000,
            intro: 'Serverless lets a fresher ship scalable back-ends with zero servers to manage — and it’s a 2026 trend.',
            concepts: ['Functions as a service', 'Cold starts', 'Event triggers', 'When serverless wins'],
            steps: ['Deploy one cloud/Vercel function.', 'Trigger it from a schedule or webhook.', 'Note its cost model vs a server.'],
            resources: [R('Vercel Functions', 'https://vercel.com/docs/functions'), R('AWS Lambda', 'https://aws.amazon.com/lambda/')] },
          { slug: 'cloud-security', title: 'Cloud security basics', read: 5, worth: 55000,
            intro: 'Security mistakes are how juniors cause outages and leaks. Knowing the basics earns instant trust.',
            concepts: ['Least-privilege IAM', 'Secrets management', 'Never commit keys', 'Backups'],
            steps: ['Make a least-privilege IAM user.', 'Move all keys to a secrets manager.', 'Add a .gitignore for env files.'],
            resources: [R('AWS IAM best practices', 'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html'), R('git-secrets', 'https://github.com/awslabs/git-secrets')] },
        ],
      },
    ],
  },
];

// helpers
export const courseBySlug = (slug) => COURSES.find((c) => c.slug === slug);
export const allTopics = (course) => course.units.flatMap((u) => u.topics.map((t) => ({ ...t, unit: u.title })));
export const topicCount = (course) => course.units.reduce((n, u) => n + u.topics.length, 0);
export const courseWorth = (course) => allTopics(course).reduce((n, t) => n + t.worth, 0);
export const globalTopicKey = (courseSlug, topicSlug) => `${courseSlug}/${topicSlug}`;
